# Generated by Django 3.1.1 on 2020-12-23 09:41

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='price',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='pictures\\movie-1.jpg', upload_to=movies.models.get_image_path),
        ),
    ]
