# Generated by Django 3.1.1 on 2020-12-23 12:25

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201223_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='static\\movie-1.jpg', upload_to=movies.models.get_image_path),
        ),
    ]
