# Generated by Django 3.1.1 on 2020-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20201224_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='total_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
