# Generated by Django 3.1.1 on 2021-01-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20210105_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema_session',
            name='release_time',
            field=models.DateTimeField(),
        ),
    ]
